### ISSUE TITLE
Something prevents modal from closing

### ISSUE THREAD

**Issue by ceremcem** [kouts/ractive-modal#1]
I'm using the `modal` component in a place, more or less [like this](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SAbAhgFwKYGcUgDQg1ANrgooAOGkA9FQMYAmAdgHQBWG9aCAlgG4zNGaFFQDmYKgGsA9gFcUGKjCS0UfNAFoAttPpIEAAV4AGZgCYq9bliUq1vTTr0JmW7i3YgAugF88BSBAAJTt1ZlppLTJpIUYFV119AAIAXiSQ1XUAWUSEAG4AHUYijPs0cMjo2PiwLgRpVPTQh2Y0AA90RnoACmAigtI0KOR0SCSAA36UAYAeACN5FBikmI1aHlpJFIKQA2YMYW6AcmiyWTIjnCSUGFk0AEodgD5pMjRGJNPzpPck2oR6klgMAtGgfD4ZlQFqQYk8prMnMk5kgDvQYtsQMCvmRwc94dMUDMyE8ABJ1BoAdWkMAQ9AAhEkAGYwSJ-clJCJRGLvFBJRiyLRzNAwIEgsEQqjE-GQxEIOHFFCTaaMHyPYqMIQAdyamQcvSmXDGRzmugAnpcpuhhqg0GNJgrZigkHMEGh5QMPYSUCb6Kb3QTPTMbv7PZ7gQBibiMpIwd6cGBkgHSXEOgNpoNgENp0OE-6AqhZnOzKgoTP4nPAqhRlNFwklmCFuves1ZyFOl1u6VzEUFruLZardbcTYYvZLUSiV3HWNdYWJ+pHR4gJ4z+NspOQ6FLRitrcDxhrDZbHZ7A4oY7Yy7XW4PZ6vd6fV7nTf9nfS2VJZGo9E7LFPnE+HiqazMS86UtStJ0pCUqpjKuT+vaqogD4QA). Think that "open popup" button works normal (in my application) but "open popup in hello" button opens the modal and then I'm unable to close it. How can I debug further?

**Comment by kouts** [comment]
The modal is appended in the root Ractive instance by default.
Try using the ```appendto``` option in order for the modal to be rendered to the body and see if that works.

**Comment by ceremcem** [comment]
I forgot to mention that, appending to `body` is not working either.

**Comment by kouts** [comment]
Can you provide a more detailed example in where is this happening?

**Comment by ceremcem** [comment]
I know it's very hard to say something without a reproduction, but I'm not able reproduce it without providing my whole project (which is not possible for me). I'll do my best to provide an example.

**Comment by kouts** [comment]
I have never encountered this behavior you are describing (and I have an
application with 94 modals in all possible places),
maybe something is conflicting in CSS, have you checked z-index?
Another thought: If you have access to the Ractive instance on the console,
try to close the modal "manually" (i.e set the value from the console) to
see if that works.

**Comment by kouts** [comment]
I'm closing this since there wasn't an example available that shows this behavior.
Feel free to reopen this if you need to.
