### ISSUE TITLE
Weird Characters instead of  Modal Close X

### ISSUE THREAD

**Issue by DavidPratten** [kouts/ractive-modal#14]
Hi @kouts, loving the library!

Could you help me with this one?

![sshot-5](https://user-images.githubusercontent.com/1667631/95664096-5c7faf00-0b90-11eb-9b75-3fb62891f239.png)

Where does the "Ã—" come from?

`<div role="dialog" aria-modal="true" class="rm" aria-label="Rename Element"><div class="rm-titlebar"><h3 class="rm-title">Rename Element</h3> <button class="rm-btn-close" type="button">
Ã—</button></div> <div class="rm-content"><div class="row"><div class="col-md-12"><label>Element Title</label> <input class="form-control" type="text" width="200px" autofocus="" value="This Project or Productxxx|Deliver This Project or Products" spellcheck="false" data-ms-editor="true"><div class="ms-editor-squiggles-container" style="all: initial;"></div></div></div> <hr class="full-hr"> <div class="row"><div class="col"><button class="btn btn-secondary" type="button">Cancel</button> <button class="btn btn-danger float-right" type="button">OK</button></div></div></div></div>`

Thanks

David

**Comment by kouts** [comment]
It's the `x` character defined here https://github.com/kouts/ractive-modal/blob/638181f2fdcb0295dceffb12066dd6c597aa426e/src/ractive-modal.ractive.html#L10
Maybe it's in a specific font that can't be displayed in your situation, you must be able to override it with CSS though targeting the `rm-btn-close` class.
Let me know if you need any help with that.

**Comment by DavidPratten** [comment]
Nice to hear from you. When I visit https://kouts.github.io/ractive-modal/demo/ it displays nicely.

![sshot-6](https://user-images.githubusercontent.com/1667631/95664343-c00adc00-0b92-11eb-98de-001c68b85d33.png)

Can you think of a reason for it being replaced by three characters? " Ã—"?

```
	<modal title="Rename Element" class="" basedon="{{renameElement.showModal}}">
		<div class="row">
			<div class="col-md-12">
				<label>Element Title</label>
				<input type="text" width="200px" value="{{renameElement.title}}" class="form-control" autofocus />
			</div>
		</div>
		<hr class="full-hr" />
		<div class="row">
			<div class="col">
				<button type="button" class="btn btn-secondary" on-click="@this.set({'renameElement.showxModal': false})">Cancel</button>
				<button type="button" class="btn btn-primary float-right" on-click="@.renameElement_callback(renameElement)">OK</button>
			</div>
		</div>
	</modal>

```

David

**Comment by kouts** [comment]
Maybe some `font-family` in the `body` that the `x` character doesn't translate well into.
I haven't encountered the issue myself, it would be great if you could replicate it in the [playground](https://ractive.js.org/playground/) or post an example so that I can take a look.

**Comment by DavidPratten** [comment]
Hi again.  Yes if you wouldn't mind having a look around that would be great.  I'm mystified!

It's not the CSS.  I disabled all CSS and the three characters are still there.

Here is a working example.

https://rosellamodel.online/r_m3684161/

Click on an element name to trigger the dialog.

![sshot-7](https://user-images.githubusercontent.com/1667631/95668684-0e37d380-0bc3-11eb-86a7-fb6b9f409a97.png)

All the best,

David

**Comment by kouts** [comment]
It's probably the document charset that needs to be set to `utf-8`.
Can you try adding `<meta charset="utf-8">`  to the `<head>` of the page?

**Comment by DavidPratten** [comment]
Hi,

Thanks for having a look around.  

Yes - that was it.

`<meta charset="utf-8">`

is required.  

I suggest adding this to documentation.

Thanks

David
