### ISSUE TITLE
Modal should not modify the scroll bar existence

### ISSUE THREAD

**Issue by ceremcem** [kouts/ractive-modal#2]
The behaviour can be observed in the [demo page](https://kouts.github.io/ractive-modal/demo/) when the first modal is opened. Before modal is opened, there is the right vertical scroll bar is appear because of page length. When modal is fired, since modal contents fit the page, the vertical scroll bar is removed (automatically). This leads a wiggling background between opening and closing of the modal (actual page moves a little bit right when modal opens (since the scroll bar is removed) and moves a little bit left (since the scroll bar is shown)). 

Proposal: 

Before modal is fired, if page has a scroll bar, then modal window should have a scroll bar.

**Comment by kouts** [comment]
This behavior is on demo only (look at the source code), just to show that you can have this functionality if
you want. By default ractive-modal will not handle window scrollbar.
