### ISSUE TITLE
Modal window can not handle large images correctly

### ISSUE THREAD

**Issue by ceremcem** [kouts/ractive-modal#4]
Following content:

```html
<modal basedon="{{mymodal}}" enableclose="{{false}}">
  <p>this is my modal content2</p>
  <img src="http://via.placeholder.com/850x150" />
</modal>
```

...causes below output: 

![image](https://user-images.githubusercontent.com/6639874/37548048-5b7ca6c4-2986-11e8-9a98-a4cbcf557590.png)

(Note: Work in progress here)

**Comment by kouts** [comment]
You can set custom CSS classes on the modal by setting the ```class``` attribute. This way you can make it look however you want, it can be "responsive" or anything you want it to be.
You can target the content area of the modal with CSS using .rm-content class
