### ISSUE TITLE
Unnecessary horizontal ruler when no title and close button is used

### ISSUE THREAD

**Issue by ceremcem** [kouts/ractive-modal#6]
If modal is initialized with `enableclose="false"` and without a title, the `<hr />` (like) element shouldn't be shown: 

![image](https://user-images.githubusercontent.com/6639874/37548378-816d63a8-2988-11e8-84e4-dd2c2c0ad89c.png)

**Comment by kouts** [comment]
Fixed 49faed36932060009ad3c4e08a643b341b6ed18e
