### ISSUE TITLE
Focus trap breaks when button element has disabled attribute

### ISSUE THREAD

**Issue by mpowell-atomic** [kouts/ractive-modal#8]
Hi! I love that there is focus trap in this modal but it breaks when a button element in the modal has the disabled attribute. This doesn't happen if an input has a disabled attribute. 

You can recreate by simply going to your demo page and simply adding the disabled attribute to any modal button.

Cheers!
Mark

**Comment by kouts** [comment]
I've tried to recreate the behavior by disabling the "Open second modal window" button, but focus trap continues to work ok.
![GIF](https://user-images.githubusercontent.com/2233663/56308594-5dc54c80-6150-11e9-97a8-8464c66a17ea.gif)

**Comment by mpowell-atomic** [comment]
@kouts Thanks for taking a look. Hmm. Interesting! Try the 'Close' button. I got the same behavior with the 'Open second window' as you but the 'Close' button (maybe the last element?) makes it skip the trap.

**Comment by kouts** [comment]
You are right @mpowell-atomic  it happens when the last button is disabled.
Thanks for the find.

**Comment by mpowell-atomic** [comment]
@kouts no problem!

**Comment by kouts** [comment]
Fixed 4c6e508a6416cd7495481fd6a55bb333b0c5ce22
