### ISSUE TITLE
Allow importing of css styles as separate file

### ISSUE THREAD

**Issue by mpowell-atomic** [kouts/ractive-modal#9]
Hi. I am having issues with custom styling of the modal because the in-component scoped <style> block has a high specificity and is hard to override it seems. Although I understand it makes it easier to use initially having the css be injected by Ractive it does make customizing the css harder.

I'd like to just be able to import your provided css file directly from the node_modules package or swap it out entirely for my own customized version.

Or maybe there's a better way! Thanks! I appreciate your work on this!

**Comment by kouts** [comment]
There is the ```class``` option use can use to pass additional CSS classes to the modal.
You can also extend the modal using [Ractive.extend](https://ractive.js.org/api/#ractiveextend) so that all modals use your custom CSS classes.

**Comment by mpowell-atomic** [comment]
Thanks for these pointers. These seem to append extra css. Ideally I'd like to replace or remove the injected styles (Your styles are fine! :-) Just don't want the injected <style> tag). Maybe a separate build without any <style> tag?

**Comment by kouts** [comment]
I see what you mean, you can of course remove the appended css via javascript on the ```oncomplete``` lifecycle event of the modal component (you must ```extend``` it), but may I ask why you need them removed?

**Comment by mpowell-atomic** [comment]
Sometimes I just want to use a normal stylesheet via <link> element in the app and not have any Ractive injected styles. That way it's easier to incorporate into existing sass setup with variables etc.

**Comment by kouts** [comment]
This is now fixed with bf5bb3578600f1f07748ff0ac29a481f9f6ee22d

**Comment by mpowell-atomic** [comment]
Fantastic! Will try it out shortly. Thanks!!
